package com.example.cinema.domain;

public enum ShowCommandError {
  SHOW_ALREADY_EXISTS,
  SHOW_NOT_FOUND,
  TOO_MANY_SEATS,
  SEAT_NOT_FOUND,
  SEAT_NOT_AVAILABLE,
  RESERVATION_NOT_FOUND,
  DUPLICATED_COMMAND,
  CANCELLING_CONFIRMED_RESERVATION
}