package com.example.cinema.domain;

public enum ShowCommandError {
  SHOW_ALREADY_EXISTS, SHOW_NOT_EXISTS, TOO_MANY_SEATS, SEAT_NOT_EXISTS, SEAT_NOT_AVAILABLE, SEAT_NOT_RESERVED, RESERVATION_NOT_FOUND, CANCELLING_PAID_SEAT_NOT_SUPPORTED
}